# Generated by Django 4.1.1 on 2022-10-03 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="diet",
            options={"ordering": ["date"]},
        ),
        migrations.AlterModelOptions(
            name="dietfood",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="food",
            options={"ordering": ["name"]},
        ),
    ]
