# Generated by Django 4.1.1 on 2022-10-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_diet_options_alter_dietfood_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diet",
            name="date",
            field=models.DateField(db_index=True),
        ),
    ]
